name: fast_track
description: A new Flutter project.


version: 1.0.0+1


environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  loading_indicator: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  curved_navigation_bar: ^1.0.3 #latest version
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  dio: ^4.0.6
  rflutter_alert: ^2.0.4


dev_dependencies:
  loading_indicator: ^3.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
    - animations/
